### PR TITLE
Milestone 2 - User interface

### PR DESCRIPTION
**Pull request by guirecordon**
We thought about the inputs we needed to receive from the users as well as the messages we needed to display.
We created a class where we added a method with a variable to store the game numbers from 1 to 9;
We also created a 2d array with the winning arrays and we created two new arrays to store the inputs of each player;
We created a method called play where we prompt the players for input and we have another method that displays the board that changes as the users add their inputs. 
We did not add any logic that would make our game work as that is part of the next Milestone. 
Thank you.

### CODE REVIEW

**Review by serdg0 — CHANGES_REQUESTED** [review]
Hello @guirecordon and @ioilmio !
In this milestone we see if you everything the game will have is covered in the plan. The scratch of what will be the game loop. This are the things we are missing:

- [x] The game should cover the detection of an invalid move.


- [x] The game should should cover the detection a winning move.


- [x] The game should cover the detection of a drawing (tie) move.


- [x] The game plan should have a mechanism to repeat turns until someone wins or tie.

Make your plan and submit for another CRR.

**Happy Coding!** :computer: :nerd_face:
**_Sergio Diaz_**

**Comment by guirecordon** [comment]
Thank you, Sergio. 
We applied the changes you requested and we're submitting for a new review.

**Review by serdg0 — APPROVED** [review]
**Congratulations** @guirecordon & @ioilmio  :fireworks: :100: :fireworks:
Feel free to merge.
As a recommendation, using numbers for the loop is a strategy prone to bugs in cases like this.
Keep the good work in your next project!
**Happy Coding!** :computer: :nerd_face:
**_Sergio Diaz_** (edited)

**Comment by guirecordon** [comment]
Thank you, Sergio. Your recommendation about using numbers in the loop was well noted.

**Pull request merged**
